"""todo list added

Revision ID: 5b527b51d4ec
Revises: 00d192d29718
Create Date: 2023-02-14 10:06:46.772196+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b527b51d4ec'
down_revision = '00d192d29718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_list_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todolist',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['todo_list_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo_list_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key("fk_todo_list_id", 'todolist', ['todo_list_id'], ['id'])

    from src.migrations.seed.status_seeders import seed_todo_list_statuses
    seed_todo_list_statuses()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint("fk_todo_list_id", type_='foreignkey')
        batch_op.drop_column('todo_list_id')

    op.drop_table('todolist')
    op.drop_table('todo_list_status')
    # ### end Alembic commands ###
